# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a006e2578c2496f948a653672289e1253a4c6ff8f23f3ad4f0acada457c9c0640e1d206a4f7bf08f5cebd382569843e66a27ea302c480735a86649b7d640c3f

test:
  secret_key_base: 082a71cb2d1795a9f5493cd878ddd2779524f9353011cc2d1c1fa007c49e1b6a52bbd5d1423f82b34bd56ef2c04375db614a390a697a0b8fac7957ccb8888822

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
